# Name of the project
PROJECT_NAME = SCIENTIFIC_CALCULATOR

#Doxyfile folder
DOC = documentation

#All source code files
SRC = calc.c\
src/calc_operations.c

#All test source files
TEST_SRC = src/calc_operations.c\
test/test_calc_operations.c\
unity/unity.c

TEST_OUTPUT = Test_fun.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = calc.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html
Build:
	gcc function.c test_calc.c -o fun.out -lm unity/unity.c -Iunity
Run:
	./fun.out